apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://host.docker.internal:9090/prometheus
    access: proxy
    isDefault: true
    editable: false
